FROM alpine:3.22

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk add --update --no-cache openssh openssh-client autossh \
  && sed -i s/#?PasswordAuthentication.*/PasswordAuthentication\ no/ /etc/ssh/sshd_config \
  && sed -i s/#?AllowTcpForwarding.*/AllowTcpForwarding\ yes/ /etc/ssh/sshd_config \
  && sed -i s/#?UseDNS.*/UseDNS\ yes/ /etc/ssh/sshd_config
